### ISSUE TITLE
Add support for custom smoke test branch

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-continuous#7]
When dealing with non-backward compatible changes, the smoke tests fail until the `project-helix.io` code has been adjusted. This is done in a branch and running the tests against the current helix-cli branch (where the backward comp change is occurring) and this project-helix.io branch makes more sense to prepare the new version and validate that everything works as expected.

The process would look like this:
* I change something in helix-cli (or one of the other project)
* If the smoke tests fail for a valid reason (non-backward comp changes), I configure the CI part of helix-cli to define which branch in project-helix.io contains the upgraded project. Smoke tests should become green again.
* once ready, I merge project-helix.io branch into master.
* I change the CI part of helix-cli back to master: smoke tests should be green again 

CI part of helix-cli (or other) to be changed has to be determined but it should be around the place we call the orb that runs the smoke tests: https://github.com/adobe/helix-cli/blob/master/.circleci/config.yml#L243-L247

@tripodsan WDYT ?

**Comment by kptdobe** [comment]
With orb `adobe/helix-smoke-tests@0.0.5`, you can now add `smoketest_branch` parameter to define which branch of the project-helix.io repo needs to be used to run the smoke tests (should be removed or back to master before the merge in master)

**Comment by tripodsan** [comment]
> you can now add smoketest_branch parameter to define which branch of the project-helix.io repo needs to be used

can you provide an example on where I would need to add this?

**Comment by kptdobe** [comment]
In the circleci config of the module you are working on (helix-cli for example), update the orb version to at least adobe/helix-smoke-tests@0.0.5` and in the job call, add the `smoketest_branch` parameter with you branch name (new_config for example). For https://github.com/adobe/helix-cli/blob/master/.circleci/config.yml, this would mean:


```
...

orbs:
  helix-smoke-tests: adobe/helix-smoke-tests@0.0.5

...

smoke:
    jobs:
    - helix-smoke-tests/run:
        token: ${SMOKE_TEST_TOKEN}
        remote_repo: adobe/helix-continuous
        smoketest_branch: new_config
```
